#cloud-config

groups:
  - docker
users:
  - name: johan
    groups: users, admin, docker
    sudo: ALL=(ALL) ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHt8EvWzOBZxA7JEQCnknW+hjEi8Id6dfMtb1ONw1xbw johan@johan-lux
yum_repos:
  docker-ce:
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    enabled: true
    name: Docker CE Stable - $basearch
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/fedora/gpg
packages:
  - fail2ban
  #- ufw
  - git
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - zsh
  - python3
  - rclone
  - sshfs
  - fuse
  - opentofu
package_update: true
package_upgrade: true
write_files:
  - path: /etc/cron.d/sysmet
    content: |
      */5 * * * * /usr/bin/sysmet-notify -vv --env /etc/sysmet/env 2>&1 >> /var/log/sysmet.log
    owner: root:root
  - path: /etc/docker/daemon.json
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64",
        "experimental": true,
        "ip6tables": true
      }
    owner: root:root
    permissions: "0644"
  - path: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled = true
      banaction = iptables-multiport
    owner: root:root
    permissions: "0644"
  - path: /etc/sysmet/env
    content: |
      MAIL_FROM=
      MAIL_CONTACTS=
      SMTP_USER=
      SMTP_PASSWORD=
      SMTP_RELAY=
      LOG_LEVEL=info

      DISK_THRESHOLD=85
  - path: /usr/lib/systemd/system/mnt-git.service
    content: |
      [Unit]
      Description=Mount remote git fs with sshfs
      After=network-online.target
      Wants=network-online.target
      Before=docker.service
      StartLimitIntervalSec=300
      StartLimitBurst=10

      [Install]
      WantedBy=multi-user.target

      [Service]
      Type=exec
      ExecStart=/usr/bin/sshfs -f {{ env "SFTP_USER" }}@{{ env "SFTP_HOST" }}:/home/forgejo/data /var/lib/docker-data/forgejo/data -p 23 -o rw,allow_other,idmap=user,uid=1000,gid=1001,ServerAliveInterval=10,ServerAliveCountMax=1,_netdev
      ExecStop=/usr/bin/umount /var/lib/docker-data/forgejo/data
      Restart=on-failure
      RestartSec=20
  - path: /usr/lib/systemd/system/mnt-seedbox.service
    content: |
      [Unit]
      Description=Mount remote seedbox fs with sshfs
      After=network-online.target
      Wants=network-online.target
      Before=docker.service
      StartLimitIntervalSec=300
      StartLimitBurst=10

      [Install]
      WantedBy=multi-user.target

      [Service]
      Type=exec
      ExecStart=/usr/bin/sshfs -f {{ env "SFTP_USER" }}@{{ env "SFTP_HOST" }}:/home/seedbox/data /var/local/docker/seedbox/data -p 23 -o rw,allow_other,idmap=user,uid=1000,gid=1001,ServerAliveInterval=10,ServerAliveCountMax=1,_netdev
      ExecStop=/usr/bin/umount /var/local/docker/seedbox/data
      Restart=on-failure
      RestartSec=20
runcmd:
  # Enable fail2ban
  - systemctl enable fail2ban
  # Enable ufw
  #- ufw allow 8080
  #- ufw enable
  # Harden SSH
  - sed -i -e '/^\(#\|\)Port/s/^.*$/Port 8080/' /etc/ssh/sshd_config
  #- sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  #- sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  #- sed -i -e '/^\(#\|\)KbdInteractiveAuthentication/s/^.*$/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config
  #- sed -i -e '/^\(#\|\)ChallengeResponseAuthentication/s/^.*$/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  #- sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  #- sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  #- sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  #- sed -i '$a AllowUsers johan' /etc/ssh/sshd_config
  # Enable and config docker with ipv6
  - systemctl enable docker
  # Install rustup
  - sudo -u johan sh -c 'curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'
  # Clone base repos
  - cd /home/johan
  - mkdir -p /home/johan/applications
  - sudo -u johan sh -c 'git clone https://github.com/joxcat/server-services.git'
  - sudo -u johan sh -c 'git clone https://github.com/joxcat/dotfiles.git'
  - |
    sudo -u johan sh -c 'git clone https://github.com/joxcat/ferrous-sysmet.git /home/johan/applications/ferrous-sysmet' && \
    pushd /home/johan/applications/ferrous-sysmet && \
    sudo -u johan sh -c 'cargo build --release' && \
    cp target/release/ferrous-sysmet /usr/local/bin && \
    popd
  - cd ~
  # Apply all config changes
  - reboot
swap:
  filename: /swap.img
  size: "auto" # or size in bytes
  maxsize: 4294967296 # size in bytes
